esphome:
  name: generic-bluetooth-proxy
  friendly_name: Generic Bluetooth Proxy
  min_version: 2025.8.0
  name_add_mac_suffix: true

esp32:
  variant: esp32
  framework:
    type: esp-idf

web_server:
  local: true
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

wifi:
  ap:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
captive_portal:

logger:

api:
#  encryption:
#    key: !secret api_encryption_key

ota:
  - platform: esphome
    id: ota_esphome
    password: !secret ota_password

esp32_ble_tracker:
# The default scan parameters are recommended.
# Aggressive scan settings (e.g., interval/window of 1100ms) typically
# provide no benefit while increasing CPU usage and may cause
# overheating.

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    id: button_safe_mode
    name: Safe Mode Boot

  - platform: factory_reset
    id: button_factory_reset
    name: Factory Reset

  - platform: restart
    id: button_restart
    name: Restart
