esphome:
  name: olimex-bluetooth-proxy
  friendly_name: Olimex Bluetooth Proxy
  min_version: 2025.8.0
  name_add_mac_suffix: true

esp32:
  board: esp32-poe-iso
  variant: esp32
  framework:
    type: esp-idf

web_server:
  local: true
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    mode: CLK_OUT
    pin: GPIO17
  phy_addr: 0
  power_pin: GPIO12

logger:
  level: DEBUG

api:
#  encryption:
#    key: !secret api_encryption_key

ota:
  - platform: esphome
    id: ota_esphome
    password: !secret ota_password

esp32_ble:
  max_connections: 4

esp32_ble_tracker:
# The default scan parameters are recommended.
# Aggressive scan settings (e.g., interval/window of 1100ms) typically
# provide no benefit while increasing CPU usage and may cause
# overheating.

bluetooth_proxy:
  active: true
  connection_slots: 4

button:
  - platform: safe_mode
    id: button_safe_mode
    name: Safe Mode Boot

  - platform: factory_reset
    id: button_factory_reset
    name: Factory Reset

  - platform: restart
    id: button_restart
    name: Restart

  - platform: template
    name: Heater Power
    id: button_heater_power
    on_press:
      - remote_transmitter.transmit_symphony:
          transmitter_id: ir_tx
          data: 0xD84
          nbits: 12
          repeat:
            times: 2
            wait_time: 0s

  - platform: template
    name: Heater Mode
    id: button_heater_mode
    on_press:
      - remote_transmitter.transmit_symphony:
          transmitter_id: ir_tx
          data: 0xD88
          nbits: 12
          repeat:
            times: 2
            wait_time: 0s

  - platform: template
    name: Heater Temp Up
    id: button_heater_temp_up
    on_press:
      - remote_transmitter.transmit_symphony:
          transmitter_id: ir_tx
          data: 0xD82
          nbits: 12
          repeat:
            times: 2
            wait_time: 0s

  - platform: template
    name: Heater Temp Down
    id: button_heater_temp_down
    on_press:
      - remote_transmitter.transmit_symphony:
          transmitter_id: ir_tx
          data: 0xD90
          nbits: 12
          repeat:
            times: 2
            wait_time: 0s

  - platform: template
    name: Heater Oscillate
    id: button_heater_oscillate
    on_press:
      - remote_transmitter.transmit_symphony:
          transmitter_id: ir_tx
          data: 0xD81
          nbits: 12
          repeat:
            times: 2
            wait_time: 0s

  - platform: template
    name: Back Porch Fan Off
    internal: true
    id: button_bp_fan_off
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(303798000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '010100000111111000100000'
          protocol:
            pulse_length: 384
            sync: [36, 1]
            zero: [1, 2]
            one: [2, 1]
            inverted: true
          repeat:
            times: 20
            wait_time: 0s

  - platform: template
    name: Back Porch Fan Speed 1
    internal: true
    id: button_bp_fan_speed1
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(303798000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '010100000111111011000000'
          protocol:
            pulse_length: 384
            sync: [36, 1]
            zero: [1, 2]
            one: [2, 1]
            inverted: true
          repeat:
            times: 20
            wait_time: 0s

  - platform: template
    name: Back Porch Fan Speed 2
    internal: true
    id: button_bp_fan_speed2
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(303798000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '010100000111111010011000'
          protocol:
            pulse_length: 384
            sync: [36, 1]
            zero: [1, 2]
            one: [2, 1]
            inverted: true
          repeat:
            times: 20
            wait_time: 0s

  - platform: template
    name: Back Porch Fan Speed 3
    internal: true
    id: button_bp_fan_speed3
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(303798000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '010100000111111001000000'
          protocol:
            pulse_length: 384
            sync: [36, 1]
            zero: [1, 2]
            one: [2, 1]
            inverted: true
          repeat:
            times: 20
            wait_time: 0s

  - platform: template
    name: Back Porch Fan Speed 4
    internal: true
    id: button_bp_fan_speed4
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(303798000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '010100000111111001010000'
          protocol:
            pulse_length: 384
            sync: [36, 1]
            zero: [1, 2]
            one: [2, 1]
            inverted: true
          repeat:
            times: 20
            wait_time: 0s

  - platform: template
    name: Back Porch Fan Speed 5
    internal: true
    id: button_bp_fan_speed5
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(303798000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '010100000111111010010100'
          protocol:
            pulse_length: 384
            sync: [36, 1]
            zero: [1, 2]
            one: [2, 1]
            inverted: true
          repeat:
            times: 20
            wait_time: 0s

  - platform: template
    name: Back Porch Fan Speed 6
    internal: true
    id: button_bp_fan_speed6
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(303798000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '010100000111111010000000'
          protocol:
            pulse_length: 384
            sync: [36, 1]
            zero: [1, 2]
            one: [2, 1]
            inverted: true
          repeat:
            times: 20
            wait_time: 0s

  - platform: template
    name: Back Porch Fan Reverse
    internal: true
    id: button_bp_fan_reverse
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(303798000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '010100000111111011010000'
          protocol:
            pulse_length: 384
            sync: [36, 1]
            zero: [1, 2]
            one: [2, 1]
            inverted: true
          repeat:
            times: 20
            wait_time: 0s

  - platform: template
    name: Bedroom 5 Fan Off
    internal: true
    id: button_br5_fan_off
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(303798000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '001010000111000100100000'
          protocol:
            pulse_length: 384
            sync: [36, 1]
            zero: [1, 2]
            one: [2, 1]
            inverted: true
          repeat:
            times: 20
            wait_time: 0s

  - platform: template
    name: Bedroom 5 Fan Speed 1
    internal: true
    id: button_br5_fan_speed1
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(303798000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '001010000111000111000000'
          protocol:
            pulse_length: 384
            sync: [36, 1]
            zero: [1, 2]
            one: [2, 1]
            inverted: true
          repeat:
            times: 20
            wait_time: 0s

  - platform: template
    name: Bedroom 5 Fan Speed 2
    internal: true
    id: button_br5_fan_speed2
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(303798000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '001010000111000110011000'
          protocol:
            pulse_length: 384
            sync: [36, 1]
            zero: [1, 2]
            one: [2, 1]
            inverted: true
          repeat:
            times: 20
            wait_time: 0s

  - platform: template
    name: Bedroom 5 Fan Speed 3
    internal: true
    id: button_br5_fan_speed3
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(303798000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '001010000111000101000000'
          protocol:
            pulse_length: 384
            sync: [36, 1]
            zero: [1, 2]
            one: [2, 1]
            inverted: true
          repeat:
            times: 20
            wait_time: 0s

  - platform: template
    name: Bedroom 5 Fan Speed 4
    internal: true
    id: button_br5_fan_speed4
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(303798000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '001010000111000101010000'
          protocol:
            pulse_length: 384
            sync: [36, 1]
            zero: [1, 2]
            one: [2, 1]
            inverted: true
          repeat:
            times: 20
            wait_time: 0s

  - platform: template
    name: Bedroom 5 Fan Speed 5
    internal: true
    id: button_br5_fan_speed5
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(303798000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '001010000111000110010100'
          protocol:
            pulse_length: 384
            sync: [36, 1]
            zero: [1, 2]
            one: [2, 1]
            inverted: true
          repeat:
            times: 20
            wait_time: 0s

  - platform: template
    name: Bedroom 5 Fan Speed 6
    internal: true
    id: button_br5_fan_speed6
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(303798000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '001010000111000110000000'
          protocol:
            pulse_length: 384
            sync: [36, 1]
            zero: [1, 2]
            one: [2, 1]
            inverted: true
          repeat:
            times: 20
            wait_time: 0s

  - platform: template
    name: Bedroom 5 Fan Reverse
    internal: true
    id: button_br5_fan_reverse
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(303798000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '001010000111000111010000'
          protocol:
            pulse_length: 384
            sync: [36, 1]
            zero: [1, 2]
            one: [2, 1]
            inverted: true
          repeat:
            times: 20
            wait_time: 0s

  - platform: template
    name: Advent Calendar On
    id: button_advent_on
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(433920000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '111111111111111100000001'
          protocol: 1
          repeat:
            times: 5
            wait_time: 0s

  - platform: template
    name: Advent Calendar Off
    id: button_advent_off
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(433920000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '111111111111111100000011'
          protocol: 1
          repeat:
            times: 5
            wait_time: 0s

  - platform: template
    name: Advent Calendar Reset
    id: button_advent_reset
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(433920000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '111111111111111100000101'
          protocol: 1
          repeat:
            times: 5
            wait_time: 0s

  - platform: template
    name: Advent Calendar Date Minus
    id: button_advent_date_minus
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(433920000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '111111111111111100000111'
          protocol: 1
          repeat:
            times: 5
            wait_time: 0s

  - platform: template
    name: Advent Calendar Date Plus
    id: button_advent_date_plus
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(433920000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '111111111111111100001001'
          protocol: 1
          repeat:
            times: 5
            wait_time: 0s

  - platform: template
    name: Advent Calendar Timer On
    id: button_advent_timer_on
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(433920000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '111111111111111100001101'
          protocol: 1
          repeat:
            times: 5
            wait_time: 0s

  - platform: template
    name: Advent Calendar Timer Off
    id: button_advent_timer_off
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(433920000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '111111111111111100001111'
          protocol: 1
          repeat:
            times: 5
            wait_time: 0s

  - platform: template
    name: Advent Calendar House Lights On
    id: button_advent_house_lights_on
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(433920000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '111111111111111100010011'
          protocol: 1
          repeat:
            times: 5
            wait_time: 0s

  - platform: template
    name: Advent Calendar House Lights Off
    id: button_advent_house_lights_off
    on_press:
      - lambda: 'id(my_cc1101).set_frequency(433920000);'
      - delay: 5ms
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: rf_tx
          code: '111111111111111100010101'
          protocol: 1
          repeat:
            times: 5
            wait_time: 0s

script:
  - id: send_bp_fan_state
    then:
      - lambda: |-
          if (id(bp_fan).state) {
            int speed = id(bp_fan).speed;
            if (speed <= 0) speed = 1;
            if (speed > 6) speed = 6;
            switch (speed) {
              case 1: id(button_bp_fan_speed1).press(); break;
              case 2: id(button_bp_fan_speed2).press(); break;
              case 3: id(button_bp_fan_speed3).press(); break;
              case 4: id(button_bp_fan_speed4).press(); break;
              case 5: id(button_bp_fan_speed5).press(); break;
              case 6: id(button_bp_fan_speed6).press(); break;
            }
          } else {
            id(button_bp_fan_off).press();
          }

  - id: send_br5_fan_state
    then:
      - lambda: |-
          if (id(br5_fan).state) {
            int speed = id(br5_fan).speed;
            if (speed <= 0) speed = 1;
            if (speed > 6) speed = 6;
            switch (speed) {
              case 1: id(button_br5_fan_speed1).press(); break;
              case 2: id(button_br5_fan_speed2).press(); break;
              case 3: id(button_br5_fan_speed3).press(); break;
              case 4: id(button_br5_fan_speed4).press(); break;
              case 5: id(button_br5_fan_speed5).press(); break;
              case 6: id(button_br5_fan_speed6).press(); break;
            }
          } else {
            id(button_br5_fan_off).press();
          }

fan:
  - platform: template
    name: "Back Porch Fan"
    id: bp_fan
    speed_count: 6
    has_direction: true
    on_turn_on:
      - script.execute: send_bp_fan_state
    on_turn_off:
      - script.execute: send_bp_fan_state
    on_speed_set:
      - lambda: |-
          auto call = id(bp_fan).turn_on();
          call.perform();
    on_direction_set:
      - button.press: button_bp_fan_reverse

  - platform: template
    name: "Bedroom 5 Fan"
    id: br5_fan
    speed_count: 6
    has_direction: true
    on_turn_on:
      - script.execute: send_br5_fan_state
    on_turn_off:
      - script.execute: send_br5_fan_state
    on_speed_set:
      - lambda: |-
          auto call = id(br5_fan).turn_on();
          call.perform();
    on_direction_set:
      - button.press: button_br5_fan_reverse

interval:
  - interval: 10s
    then:
      - script.execute: send_bp_fan_state
      - delay: 2s
      - script.execute: send_br5_fan_state

# CC1101 Wiring (via UEXT 10-pin IDC breakout cable)
#   CC1101 pin 1 (GND)  → UEXT pin 2  (GND)    → grey
#   CC1101 pin 2 (VCC)  → UEXT pin 1  (3.3V)   → purple
#   CC1101 pin 3 (GDO0) → UEXT pin 3  (GPIO4)  → blue    (TX)
#   CC1101 pin 4 (CSN)  → UEXT pin 10 (GPIO5)  → white
#   CC1101 pin 5 (SCK)  → UEXT pin 9  (GPIO14) → black
#   CC1101 pin 6 (MOSI) → UEXT pin 8  (GPIO2)  → brown
#   CC1101 pin 7 (MISO) → UEXT pin 7  (GPIO15) → red
#   CC1101 pin 8 (GDO2) → UEXT pin 4  (GPIO36) → green   (RX)

# SPI bus for CC1101
spi:
  clk_pin: GPIO14
  mosi_pin: GPIO2
  miso_pin: GPIO15

# CC1101 RF
cc1101:
  id: my_cc1101
  cs_pin: GPIO5
  frequency: 433.92MHz
  modulation_type: ASK/OOK

number:
  - platform: template
    name: "CC1101 Frequency"
    id: cc1101_frequency
    unit_of_measurement: "MHz"
    min_value: 300
    max_value: 928
    step: 0.001
    initial_value: 433.92
    restore_value: true
    optimistic: true
    mode: box
    on_value:
      then:
        - lambda: 'id(my_cc1101).set_frequency(x * 1000000);'
        - cc1101.begin_rx
        - logger.log:
            format: "CC1101 frequency set to %.3f MHz"
            args: ['x']

remote_transmitter:
  # IR Transmitter (EXT1 GPIO33)
  - id: ir_tx
    pin: GPIO33
    carrier_duty_percent: 50%

  # RF Transmitter (CC1101 GDO0)
  - id: rf_tx
    pin: GPIO4
    carrier_duty_percent: 100%
    non_blocking: false
    on_transmit:
      then:
        - cc1101.begin_tx
    on_complete:
      then:
        - lambda: 'id(my_cc1101).set_frequency(id(cc1101_frequency).state * 1000000);'
        - cc1101.begin_rx

remote_receiver:
  # IR Receiver (GPIO32)
  - id: ir_rx
    pin:
      number: GPIO32
      inverted: true
    dump: all
    tolerance: 25%
    filter: 50us
    idle: 10ms

  # RF Receiver (CC1101 GDO2)
  - id: rf_rx
    pin:
      number: GPIO36
      inverted: true
    dump: all
    tolerance: 50%
    filter: 250us
    idle: 4ms
